import type { Property, NotificationItem, KPI, User } from "./types";

export const currentUser: User = {
  id: "u_001",
  name: "Ananya Sharma",
  email: "ananya@terratrust.ai",
  role: "citizen",
  region: "Bengaluru, India",
  verified: true,
  joinedAt: "2024-03-12",
};

export const properties: Property[] = [
  {
    id: "p_001",
    passportId: "TT-8421-LG",
    title: "Indiranagar Residence",
    type: "residential",
    status: "verified",
    trustScore: 96,
    area: 540,
    address: "12 100 Feet Road, Indiranagar",
    region: "Bengaluru",
    country: "India",
    owner: "Ananya Sharma",
    ownerSince: "2019-06-14",
    valuation: 285000,
    aiConfidence: 92,
    coords: { lat: 12.9716, lng: 77.5946 },
    boundary: [
      { lat: 12.9717, lng: 77.5944 },
      { lat: 12.9718, lng: 77.595 },
      { lat: 12.9714, lng: 77.5951 },
      { lat: 12.9713, lng: 77.5945 },
    ],
    documents: [
      {
        id: "d1",
        name: "Registered Sale Deed.pdf",
        kind: "deed",
        uploadedAt: "2024-03-14",
        verified: true,
      },
      {
        id: "d2",
        name: "Survey Plan 2023.pdf",
        kind: "survey",
        uploadedAt: "2023-11-02",
        verified: true,
      },
      {
        id: "d3",
        name: "Property Tax Receipt 2024.pdf",
        kind: "tax",
        uploadedAt: "2024-08-19",
        verified: true,
      },
    ],
    timeline: [
      {
        id: "t1",
        actor: "Bengaluru Land Records",
        role: "officer",
        action: "Ownership confirmed on registry",
        at: "2024-03-20",
      },
      {
        id: "t2",
        actor: "Surveyor Rohan Mehta",
        role: "surveyor",
        action: "GIS boundary uploaded & verified",
        at: "2024-03-15",
      },
      {
        id: "t3",
        actor: "TerraTrust AI",
        role: "admin",
        action: "AI valuation generated",
        at: "2024-03-15",
      },
      {
        id: "t4",
        actor: "Resident Welfare Association",
        role: "verifier",
        action: "Neighborhood attestation received",
        at: "2024-04-02",
      },
    ],
    tags: ["Family home", "Mortgage-eligible"],
  },
  {
    id: "p_002",
    passportId: "TT-2210-KD",
    title: "Pune Agricultural Parcel",
    type: "agricultural",
    status: "pending",
    trustScore: 71,
    area: 12400,
    address: "Plot 14, Mulshi Road",
    region: "Pune",
    country: "India",
    owner: "Ananya Sharma",
    ownerSince: "2022-01-09",
    valuation: 48500,
    aiConfidence: 78,
    coords: { lat: 18.5204, lng: 73.8567 },
    boundary: [],
    documents: [
      {
        id: "d4",
        name: "7/12 Extract.pdf",
        kind: "deed",
        uploadedAt: "2024-09-10",
        verified: false,
      },
    ],
    timeline: [
      {
        id: "t5",
        actor: "Ananya Sharma",
        role: "citizen",
        action: "Property submitted for verification",
        at: "2024-09-10",
      },
      {
        id: "t6",
        actor: "TerraTrust AI",
        role: "admin",
        action: "OCR completed on 1 document",
        at: "2024-09-10",
      },
    ],
    tags: ["Family land"],
  },
  {
    id: "p_003",
    passportId: "TT-5512-AB",
    title: "Delhi Commercial Plot",
    type: "commercial",
    status: "disputed",
    trustScore: 42,
    area: 1800,
    address: "Plot 88, Vasant Kunj",
    region: "Delhi",
    country: "India",
    owner: "Ananya Sharma",
    ownerSince: "2021-05-22",
    valuation: 612000,
    aiConfidence: 65,
    coords: { lat: 28.6139, lng: 77.209 },
    boundary: [],
    documents: [
      { id: "d5", name: "Sale Deed.pdf", kind: "deed", uploadedAt: "2023-02-11", verified: true },
      {
        id: "d6",
        name: "Conflicting claim notice.pdf",
        kind: "other",
        uploadedAt: "2024-07-30",
        verified: false,
      },
    ],
    timeline: [
      {
        id: "t7",
        actor: "Delhi Land Records",
        role: "officer",
        action: "Dispute flagged — overlapping claim detected",
        at: "2024-07-30",
      },
      {
        id: "t8",
        actor: "TerraTrust AI",
        role: "admin",
        action: "Boundary conflict detected via GIS",
        at: "2024-07-30",
      },
    ],
    tags: ["Under dispute"],
  },
  {
    id: "p_004",
    passportId: "TT-9930-OY",
    title: "Hyderabad Family Home",
    type: "residential",
    status: "verified",
    trustScore: 88,
    area: 880,
    address: "23 Banjara Hills",
    region: "Hyderabad",
    country: "India",
    owner: "Ananya Sharma",
    ownerSince: "2015-11-30",
    valuation: 142000,
    aiConfidence: 90,
    coords: { lat: 17.385, lng: 78.4867 },
    boundary: [],
    documents: [
      { id: "d7", name: "Gift Deed.pdf", kind: "deed", uploadedAt: "2022-04-01", verified: true },
    ],
    timeline: [
      {
        id: "t9",
        actor: "Telangana Land Records",
        role: "officer",
        action: "Title confirmed",
        at: "2022-04-12",
      },
    ],
    tags: ["Inherited"],
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    title: "Verification complete",
    body: "Indiranagar Residence trust score updated to 96.",
    at: "2 hours ago",
    read: false,
    kind: "success",
  },
  {
    id: "n2",
    title: "New community attestation",
    body: "Banjara Hills Home received 3 neighborhood attestations.",
    at: "Yesterday",
    read: false,
    kind: "info",
  },
  {
    id: "n3",
    title: "Action needed",
    body: "Upload the property tax receipt for the Pune parcel to raise trust score.",
    at: "2 days ago",
    read: true,
    kind: "warning",
  },
  {
    id: "n4",
    title: "Dispute filed",
    body: "An overlapping claim was registered on the Delhi commercial plot.",
    at: "Last week",
    read: true,
    kind: "alert",
  },
];

export const citizenKpis: KPI[] = [
  { label: "Properties", value: "4", delta: "+1", trend: "up", hint: "in your portfolio" },
  { label: "Avg. trust score", value: "74", delta: "+6", trend: "up", hint: "rolling 30 days" },
  { label: "Portfolio value", value: "₹1.08M", delta: "+4.2%", trend: "up", hint: "AI estimate" },
  { label: "Open actions", value: "3", delta: "-1", trend: "down", hint: "verification tasks" },
];
export const govKpis: KPI[] = [
  { label: "Registered parcels", value: "2.4M", delta: "+18k", trend: "up" },
  { label: "Verifications / day", value: "9,184", delta: "+12%", trend: "up" },
  { label: "Disputes resolved", value: "612", delta: "+44", trend: "up" },
  { label: "Fraud flags", value: "27", delta: "-9", trend: "down" },
];
export const surveyorKpis: KPI[] = [
  { label: "Active assignments", value: "12", trend: "flat" },
  { label: "Completed this month", value: "38", delta: "+5", trend: "up" },
  { label: "Avg. turnaround", value: "2.4d", delta: "-0.3d", trend: "down" },
  { label: "Quality score", value: "4.92", delta: "+0.04", trend: "up" },
];
export const adminKpis: KPI[] = [
  { label: "Active users", value: "184,221", delta: "+3.1%", trend: "up" },
  { label: "Properties indexed", value: "2.41M", delta: "+0.7%", trend: "up" },
  { label: "AI requests / day", value: "1.2M", delta: "+8%", trend: "up" },
  { label: "Uptime", value: "99.98%", trend: "flat" },
];
export const verificationsOverTime = [
  { month: "Jan", verified: 6200, pending: 1800, disputed: 240 },
  { month: "Feb", verified: 7100, pending: 1600, disputed: 220 },
  { month: "Mar", verified: 7800, pending: 1500, disputed: 210 },
  { month: "Apr", verified: 8600, pending: 1400, disputed: 190 },
  { month: "May", verified: 9100, pending: 1320, disputed: 180 },
  { month: "Jun", verified: 9800, pending: 1240, disputed: 170 },
  { month: "Jul", verified: 10400, pending: 1180, disputed: 165 },
  { month: "Aug", verified: 11200, pending: 1100, disputed: 158 },
];
export const valuationTrend = [
  { year: "2019", value: 180 },
  { year: "2020", value: 198 },
  { year: "2021", value: 222 },
  { year: "2022", value: 244 },
  { year: "2023", value: 261 },
  { year: "2024", value: 285 },
];
export const trustDistribution = [
  { name: "90–100", value: 38 },
  { name: "70–89", value: 32 },
  { name: "50–69", value: 18 },
  { name: "< 50", value: 12 },
];
export const regions = [
  { name: "Bengaluru", verified: 412000, pending: 38000 },
  { name: "Delhi", verified: 184000, pending: 22000 },
  { name: "Mumbai", verified: 268000, pending: 41000 },
  { name: "Hyderabad", verified: 198000, pending: 27000 },
  { name: "Pune", verified: 142000, pending: 35000 },
  { name: "Chennai", verified: 156000, pending: 24000 },
];
