/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SurveyorRouteImport } from './routes/surveyor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as EmptyRouteImport } from './routes/empty'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BankRouteImport } from './routes/bank'
import { Route as AttestationsRouteImport } from './routes/attestations'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApiTokensRouteImport } from './routes/api-tokens'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiValuationRouteImport } from './routes/ai-valuation'
import { Route as AiTimelineRouteImport } from './routes/ai-timeline'
import { Route as AiSummaryRouteImport } from './routes/ai-summary'
import { Route as AiSuggestionsRouteImport } from './routes/ai-suggestions'
import { Route as AiSatelliteRouteImport } from './routes/ai-satellite'
import { Route as AiRiskRouteImport } from './routes/ai-risk'
import { Route as AiRecommendationsRouteImport } from './routes/ai-recommendations'
import { Route as AiPassportRouteImport } from './routes/ai-passport'
import { Route as AiOcrRouteImport } from './routes/ai-ocr'
import { Route as AiLandHealthRouteImport } from './routes/ai-land-health'
import { Route as AiFraudRouteImport } from './routes/ai-fraud'
import { Route as AiConfidenceRouteImport } from './routes/ai-confidence'
import { Route as AiBoundaryRouteImport } from './routes/ai-boundary'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyorToolsRouteImport } from './routes/surveyor.tools'
import { Route as SurveyorAssignmentsRouteImport } from './routes/surveyor.assignments'
import { Route as SupportNewRouteImport } from './routes/support.new'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as ReportsNewRouteImport } from './routes/reports.new'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as GovernmentPermitsRouteImport } from './routes/government.permits'
import { Route as GovernmentParcelsRouteImport } from './routes/government.parcels'
import { Route as GovernmentDisputesRouteImport } from './routes/government.disputes'
import { Route as GovernmentAuditRouteImport } from './routes/government.audit'
import { Route as FraudIdRouteImport } from './routes/fraud.$id'
import { Route as DisputesNewRouteImport } from './routes/disputes.new'
import { Route as DisputesIdRouteImport } from './routes/disputes.$id'
import { Route as BankLoansRouteImport } from './routes/bank.loans'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRegionsRouteImport } from './routes/admin.regions'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as SurveyorAssignmentsIdRouteImport } from './routes/surveyor.assignments.$id'
import { Route as PropertiesIdVerifyRouteImport } from './routes/properties.$id.verify'
import { Route as PropertiesIdTransferRouteImport } from './routes/properties.$id.transfer'
import { Route as PropertiesIdTimelineRouteImport } from './routes/properties.$id.timeline'
import { Route as PropertiesIdShareRouteImport } from './routes/properties.$id.share'
import { Route as PropertiesIdSatelliteRouteImport } from './routes/properties.$id.satellite'
import { Route as PropertiesIdPassportPdfRouteImport } from './routes/properties.$id.passport-pdf'
import { Route as PropertiesIdOwnershipRouteImport } from './routes/properties.$id.ownership'
import { Route as PropertiesIdGisLayersRouteImport } from './routes/properties.$id.gis-layers'
import { Route as PropertiesIdDocumentsRouteImport } from './routes/properties.$id.documents'
import { Route as PropertiesIdBoundaryRouteImport } from './routes/properties.$id.boundary'
import { Route as PropertiesIdAiAnalysisRouteImport } from './routes/properties.$id.ai-analysis'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyorRoute = SurveyorRouteImport.update({
  id: '/surveyor',
  path: '/surveyor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoute = EmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AttestationsRoute = AttestationsRouteImport.update({
  id: '/attestations',
  path: '/attestations',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiValuationRoute = AiValuationRouteImport.update({
  id: '/ai-valuation',
  path: '/ai-valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTimelineRoute = AiTimelineRouteImport.update({
  id: '/ai-timeline',
  path: '/ai-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSummaryRoute = AiSummaryRouteImport.update({
  id: '/ai-summary',
  path: '/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSuggestionsRoute = AiSuggestionsRouteImport.update({
  id: '/ai-suggestions',
  path: '/ai-suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSatelliteRoute = AiSatelliteRouteImport.update({
  id: '/ai-satellite',
  path: '/ai-satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRiskRoute = AiRiskRouteImport.update({
  id: '/ai-risk',
  path: '/ai-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationsRoute = AiRecommendationsRouteImport.update({
  id: '/ai-recommendations',
  path: '/ai-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPassportRoute = AiPassportRouteImport.update({
  id: '/ai-passport',
  path: '/ai-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const AiOcrRoute = AiOcrRouteImport.update({
  id: '/ai-ocr',
  path: '/ai-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLandHealthRoute = AiLandHealthRouteImport.update({
  id: '/ai-land-health',
  path: '/ai-land-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFraudRoute = AiFraudRouteImport.update({
  id: '/ai-fraud',
  path: '/ai-fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConfidenceRoute = AiConfidenceRouteImport.update({
  id: '/ai-confidence',
  path: '/ai-confidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBoundaryRoute = AiBoundaryRouteImport.update({
  id: '/ai-boundary',
  path: '/ai-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyorToolsRoute = SurveyorToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SurveyorRoute,
} as any)
const SurveyorAssignmentsRoute = SurveyorAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => SurveyorRoute,
} as any)
const SupportNewRoute = SupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupportRoute,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupportRoute,
} as any)
const ReportsNewRoute = ReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const GovernmentPermitsRoute = GovernmentPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => GovernmentRoute,
} as any)
const GovernmentParcelsRoute = GovernmentParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => GovernmentRoute,
} as any)
const GovernmentDisputesRoute = GovernmentDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => GovernmentRoute,
} as any)
const GovernmentAuditRoute = GovernmentAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => GovernmentRoute,
} as any)
const FraudIdRoute = FraudIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FraudRoute,
} as any)
const DisputesNewRoute = DisputesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DisputesRoute,
} as any)
const DisputesIdRoute = DisputesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DisputesRoute,
} as any)
const BankLoansRoute = BankLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => BankRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const SurveyorAssignmentsIdRoute = SurveyorAssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SurveyorAssignmentsRoute,
} as any)
const PropertiesIdVerifyRoute = PropertiesIdVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdTransferRoute = PropertiesIdTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdTimelineRoute = PropertiesIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdShareRoute = PropertiesIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdSatelliteRoute = PropertiesIdSatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdPassportPdfRoute = PropertiesIdPassportPdfRouteImport.update({
  id: '/passport-pdf',
  path: '/passport-pdf',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdOwnershipRoute = PropertiesIdOwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdGisLayersRoute = PropertiesIdGisLayersRouteImport.update({
  id: '/gis-layers',
  path: '/gis-layers',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdDocumentsRoute = PropertiesIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdBoundaryRoute = PropertiesIdBoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const PropertiesIdAiAnalysisRoute = PropertiesIdAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => PropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/ai-boundary': typeof AiBoundaryRoute
  '/ai-confidence': typeof AiConfidenceRoute
  '/ai-fraud': typeof AiFraudRoute
  '/ai-land-health': typeof AiLandHealthRoute
  '/ai-ocr': typeof AiOcrRoute
  '/ai-passport': typeof AiPassportRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/ai-risk': typeof AiRiskRoute
  '/ai-satellite': typeof AiSatelliteRoute
  '/ai-suggestions': typeof AiSuggestionsRoute
  '/ai-summary': typeof AiSummaryRoute
  '/ai-timeline': typeof AiTimelineRoute
  '/ai-valuation': typeof AiValuationRoute
  '/analytics': typeof AnalyticsRoute
  '/api-tokens': typeof ApiTokensRoute
  '/assistant': typeof AssistantRoute
  '/attestations': typeof AttestationsRoute
  '/bank': typeof BankRouteWithChildren
  '/billing': typeof BillingRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/empty': typeof EmptyRoute
  '/error': typeof ErrorRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud': typeof FraudRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/integrations': typeof IntegrationsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRouteWithChildren
  '/surveyor': typeof SurveyorRouteWithChildren
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/verification': typeof VerificationRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/bank/loans': typeof BankLoansRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/fraud/$id': typeof FraudIdRoute
  '/government/audit': typeof GovernmentAuditRoute
  '/government/disputes': typeof GovernmentDisputesRoute
  '/government/parcels': typeof GovernmentParcelsRoute
  '/government/permits': typeof GovernmentPermitsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/support/$id': typeof SupportIdRoute
  '/support/new': typeof SupportNewRoute
  '/surveyor/assignments': typeof SurveyorAssignmentsRouteWithChildren
  '/surveyor/tools': typeof SurveyorToolsRoute
  '/properties/$id/ai-analysis': typeof PropertiesIdAiAnalysisRoute
  '/properties/$id/boundary': typeof PropertiesIdBoundaryRoute
  '/properties/$id/documents': typeof PropertiesIdDocumentsRoute
  '/properties/$id/gis-layers': typeof PropertiesIdGisLayersRoute
  '/properties/$id/ownership': typeof PropertiesIdOwnershipRoute
  '/properties/$id/passport-pdf': typeof PropertiesIdPassportPdfRoute
  '/properties/$id/satellite': typeof PropertiesIdSatelliteRoute
  '/properties/$id/share': typeof PropertiesIdShareRoute
  '/properties/$id/timeline': typeof PropertiesIdTimelineRoute
  '/properties/$id/transfer': typeof PropertiesIdTransferRoute
  '/properties/$id/verify': typeof PropertiesIdVerifyRoute
  '/surveyor/assignments/$id': typeof SurveyorAssignmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/ai-boundary': typeof AiBoundaryRoute
  '/ai-confidence': typeof AiConfidenceRoute
  '/ai-fraud': typeof AiFraudRoute
  '/ai-land-health': typeof AiLandHealthRoute
  '/ai-ocr': typeof AiOcrRoute
  '/ai-passport': typeof AiPassportRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/ai-risk': typeof AiRiskRoute
  '/ai-satellite': typeof AiSatelliteRoute
  '/ai-suggestions': typeof AiSuggestionsRoute
  '/ai-summary': typeof AiSummaryRoute
  '/ai-timeline': typeof AiTimelineRoute
  '/ai-valuation': typeof AiValuationRoute
  '/analytics': typeof AnalyticsRoute
  '/api-tokens': typeof ApiTokensRoute
  '/assistant': typeof AssistantRoute
  '/attestations': typeof AttestationsRoute
  '/bank': typeof BankRouteWithChildren
  '/billing': typeof BillingRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/empty': typeof EmptyRoute
  '/error': typeof ErrorRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud': typeof FraudRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/integrations': typeof IntegrationsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRouteWithChildren
  '/surveyor': typeof SurveyorRouteWithChildren
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/verification': typeof VerificationRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/bank/loans': typeof BankLoansRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/fraud/$id': typeof FraudIdRoute
  '/government/audit': typeof GovernmentAuditRoute
  '/government/disputes': typeof GovernmentDisputesRoute
  '/government/parcels': typeof GovernmentParcelsRoute
  '/government/permits': typeof GovernmentPermitsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/support/$id': typeof SupportIdRoute
  '/support/new': typeof SupportNewRoute
  '/surveyor/assignments': typeof SurveyorAssignmentsRouteWithChildren
  '/surveyor/tools': typeof SurveyorToolsRoute
  '/properties/$id/ai-analysis': typeof PropertiesIdAiAnalysisRoute
  '/properties/$id/boundary': typeof PropertiesIdBoundaryRoute
  '/properties/$id/documents': typeof PropertiesIdDocumentsRoute
  '/properties/$id/gis-layers': typeof PropertiesIdGisLayersRoute
  '/properties/$id/ownership': typeof PropertiesIdOwnershipRoute
  '/properties/$id/passport-pdf': typeof PropertiesIdPassportPdfRoute
  '/properties/$id/satellite': typeof PropertiesIdSatelliteRoute
  '/properties/$id/share': typeof PropertiesIdShareRoute
  '/properties/$id/timeline': typeof PropertiesIdTimelineRoute
  '/properties/$id/transfer': typeof PropertiesIdTransferRoute
  '/properties/$id/verify': typeof PropertiesIdVerifyRoute
  '/surveyor/assignments/$id': typeof SurveyorAssignmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/ai-boundary': typeof AiBoundaryRoute
  '/ai-confidence': typeof AiConfidenceRoute
  '/ai-fraud': typeof AiFraudRoute
  '/ai-land-health': typeof AiLandHealthRoute
  '/ai-ocr': typeof AiOcrRoute
  '/ai-passport': typeof AiPassportRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/ai-risk': typeof AiRiskRoute
  '/ai-satellite': typeof AiSatelliteRoute
  '/ai-suggestions': typeof AiSuggestionsRoute
  '/ai-summary': typeof AiSummaryRoute
  '/ai-timeline': typeof AiTimelineRoute
  '/ai-valuation': typeof AiValuationRoute
  '/analytics': typeof AnalyticsRoute
  '/api-tokens': typeof ApiTokensRoute
  '/assistant': typeof AssistantRoute
  '/attestations': typeof AttestationsRoute
  '/bank': typeof BankRouteWithChildren
  '/billing': typeof BillingRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/disputes': typeof DisputesRouteWithChildren
  '/empty': typeof EmptyRoute
  '/error': typeof ErrorRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud': typeof FraudRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/integrations': typeof IntegrationsRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/role-select': typeof RoleSelectRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/success': typeof SuccessRoute
  '/support': typeof SupportRouteWithChildren
  '/surveyor': typeof SurveyorRouteWithChildren
  '/terms': typeof TermsRoute
  '/valuation': typeof ValuationRoute
  '/verification': typeof VerificationRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/bank/loans': typeof BankLoansRoute
  '/disputes/$id': typeof DisputesIdRoute
  '/disputes/new': typeof DisputesNewRoute
  '/fraud/$id': typeof FraudIdRoute
  '/government/audit': typeof GovernmentAuditRoute
  '/government/disputes': typeof GovernmentDisputesRoute
  '/government/parcels': typeof GovernmentParcelsRoute
  '/government/permits': typeof GovernmentPermitsRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/new': typeof PropertiesNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/new': typeof ReportsNewRoute
  '/support/$id': typeof SupportIdRoute
  '/support/new': typeof SupportNewRoute
  '/surveyor/assignments': typeof SurveyorAssignmentsRouteWithChildren
  '/surveyor/tools': typeof SurveyorToolsRoute
  '/properties/$id/ai-analysis': typeof PropertiesIdAiAnalysisRoute
  '/properties/$id/boundary': typeof PropertiesIdBoundaryRoute
  '/properties/$id/documents': typeof PropertiesIdDocumentsRoute
  '/properties/$id/gis-layers': typeof PropertiesIdGisLayersRoute
  '/properties/$id/ownership': typeof PropertiesIdOwnershipRoute
  '/properties/$id/passport-pdf': typeof PropertiesIdPassportPdfRoute
  '/properties/$id/satellite': typeof PropertiesIdSatelliteRoute
  '/properties/$id/share': typeof PropertiesIdShareRoute
  '/properties/$id/timeline': typeof PropertiesIdTimelineRoute
  '/properties/$id/transfer': typeof PropertiesIdTransferRoute
  '/properties/$id/verify': typeof PropertiesIdVerifyRoute
  '/surveyor/assignments/$id': typeof SurveyorAssignmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/ai-boundary'
    | '/ai-confidence'
    | '/ai-fraud'
    | '/ai-land-health'
    | '/ai-ocr'
    | '/ai-passport'
    | '/ai-recommendations'
    | '/ai-risk'
    | '/ai-satellite'
    | '/ai-suggestions'
    | '/ai-summary'
    | '/ai-timeline'
    | '/ai-valuation'
    | '/analytics'
    | '/api-tokens'
    | '/assistant'
    | '/attestations'
    | '/bank'
    | '/billing'
    | '/changelog'
    | '/community'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/disputes'
    | '/empty'
    | '/error'
    | '/feedback'
    | '/forgot-password'
    | '/fraud'
    | '/government'
    | '/help'
    | '/impact'
    | '/integrations'
    | '/loading'
    | '/login'
    | '/map'
    | '/mobile'
    | '/notifications'
    | '/onboarding'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/reports'
    | '/roadmap'
    | '/role-select'
    | '/search'
    | '/security'
    | '/settings'
    | '/status'
    | '/success'
    | '/support'
    | '/surveyor'
    | '/terms'
    | '/valuation'
    | '/verification'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/system'
    | '/admin/users'
    | '/bank/loans'
    | '/disputes/$id'
    | '/disputes/new'
    | '/fraud/$id'
    | '/government/audit'
    | '/government/disputes'
    | '/government/parcels'
    | '/government/permits'
    | '/properties/$id'
    | '/properties/new'
    | '/reports/$id'
    | '/reports/new'
    | '/support/$id'
    | '/support/new'
    | '/surveyor/assignments'
    | '/surveyor/tools'
    | '/properties/$id/ai-analysis'
    | '/properties/$id/boundary'
    | '/properties/$id/documents'
    | '/properties/$id/gis-layers'
    | '/properties/$id/ownership'
    | '/properties/$id/passport-pdf'
    | '/properties/$id/satellite'
    | '/properties/$id/share'
    | '/properties/$id/timeline'
    | '/properties/$id/transfer'
    | '/properties/$id/verify'
    | '/surveyor/assignments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/ai-boundary'
    | '/ai-confidence'
    | '/ai-fraud'
    | '/ai-land-health'
    | '/ai-ocr'
    | '/ai-passport'
    | '/ai-recommendations'
    | '/ai-risk'
    | '/ai-satellite'
    | '/ai-suggestions'
    | '/ai-summary'
    | '/ai-timeline'
    | '/ai-valuation'
    | '/analytics'
    | '/api-tokens'
    | '/assistant'
    | '/attestations'
    | '/bank'
    | '/billing'
    | '/changelog'
    | '/community'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/disputes'
    | '/empty'
    | '/error'
    | '/feedback'
    | '/forgot-password'
    | '/fraud'
    | '/government'
    | '/help'
    | '/impact'
    | '/integrations'
    | '/loading'
    | '/login'
    | '/map'
    | '/mobile'
    | '/notifications'
    | '/onboarding'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/reports'
    | '/roadmap'
    | '/role-select'
    | '/search'
    | '/security'
    | '/settings'
    | '/status'
    | '/success'
    | '/support'
    | '/surveyor'
    | '/terms'
    | '/valuation'
    | '/verification'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/system'
    | '/admin/users'
    | '/bank/loans'
    | '/disputes/$id'
    | '/disputes/new'
    | '/fraud/$id'
    | '/government/audit'
    | '/government/disputes'
    | '/government/parcels'
    | '/government/permits'
    | '/properties/$id'
    | '/properties/new'
    | '/reports/$id'
    | '/reports/new'
    | '/support/$id'
    | '/support/new'
    | '/surveyor/assignments'
    | '/surveyor/tools'
    | '/properties/$id/ai-analysis'
    | '/properties/$id/boundary'
    | '/properties/$id/documents'
    | '/properties/$id/gis-layers'
    | '/properties/$id/ownership'
    | '/properties/$id/passport-pdf'
    | '/properties/$id/satellite'
    | '/properties/$id/share'
    | '/properties/$id/timeline'
    | '/properties/$id/transfer'
    | '/properties/$id/verify'
    | '/surveyor/assignments/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/ai-boundary'
    | '/ai-confidence'
    | '/ai-fraud'
    | '/ai-land-health'
    | '/ai-ocr'
    | '/ai-passport'
    | '/ai-recommendations'
    | '/ai-risk'
    | '/ai-satellite'
    | '/ai-suggestions'
    | '/ai-summary'
    | '/ai-timeline'
    | '/ai-valuation'
    | '/analytics'
    | '/api-tokens'
    | '/assistant'
    | '/attestations'
    | '/bank'
    | '/billing'
    | '/changelog'
    | '/community'
    | '/complete-profile'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/disputes'
    | '/empty'
    | '/error'
    | '/feedback'
    | '/forgot-password'
    | '/fraud'
    | '/government'
    | '/help'
    | '/impact'
    | '/integrations'
    | '/loading'
    | '/login'
    | '/map'
    | '/mobile'
    | '/notifications'
    | '/onboarding'
    | '/partners'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/properties'
    | '/register'
    | '/reports'
    | '/roadmap'
    | '/role-select'
    | '/search'
    | '/security'
    | '/settings'
    | '/status'
    | '/success'
    | '/support'
    | '/surveyor'
    | '/terms'
    | '/valuation'
    | '/verification'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/feedback'
    | '/admin/regions'
    | '/admin/roles'
    | '/admin/system'
    | '/admin/users'
    | '/bank/loans'
    | '/disputes/$id'
    | '/disputes/new'
    | '/fraud/$id'
    | '/government/audit'
    | '/government/disputes'
    | '/government/parcels'
    | '/government/permits'
    | '/properties/$id'
    | '/properties/new'
    | '/reports/$id'
    | '/reports/new'
    | '/support/$id'
    | '/support/new'
    | '/surveyor/assignments'
    | '/surveyor/tools'
    | '/properties/$id/ai-analysis'
    | '/properties/$id/boundary'
    | '/properties/$id/documents'
    | '/properties/$id/gis-layers'
    | '/properties/$id/ownership'
    | '/properties/$id/passport-pdf'
    | '/properties/$id/satellite'
    | '/properties/$id/share'
    | '/properties/$id/timeline'
    | '/properties/$id/transfer'
    | '/properties/$id/verify'
    | '/surveyor/assignments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  AiBoundaryRoute: typeof AiBoundaryRoute
  AiConfidenceRoute: typeof AiConfidenceRoute
  AiFraudRoute: typeof AiFraudRoute
  AiLandHealthRoute: typeof AiLandHealthRoute
  AiOcrRoute: typeof AiOcrRoute
  AiPassportRoute: typeof AiPassportRoute
  AiRecommendationsRoute: typeof AiRecommendationsRoute
  AiRiskRoute: typeof AiRiskRoute
  AiSatelliteRoute: typeof AiSatelliteRoute
  AiSuggestionsRoute: typeof AiSuggestionsRoute
  AiSummaryRoute: typeof AiSummaryRoute
  AiTimelineRoute: typeof AiTimelineRoute
  AiValuationRoute: typeof AiValuationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiTokensRoute: typeof ApiTokensRoute
  AssistantRoute: typeof AssistantRoute
  AttestationsRoute: typeof AttestationsRoute
  BankRoute: typeof BankRouteWithChildren
  BillingRoute: typeof BillingRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityRoute: typeof CommunityRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DisputesRoute: typeof DisputesRouteWithChildren
  EmptyRoute: typeof EmptyRoute
  ErrorRoute: typeof ErrorRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FraudRoute: typeof FraudRouteWithChildren
  GovernmentRoute: typeof GovernmentRouteWithChildren
  HelpRoute: typeof HelpRoute
  ImpactRoute: typeof ImpactRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MobileRoute: typeof MobileRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  RoleSelectRoute: typeof RoleSelectRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SuccessRoute: typeof SuccessRoute
  SupportRoute: typeof SupportRouteWithChildren
  SurveyorRoute: typeof SurveyorRouteWithChildren
  TermsRoute: typeof TermsRoute
  ValuationRoute: typeof ValuationRoute
  VerificationRoute: typeof VerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyor': {
      id: '/surveyor'
      path: '/surveyor'
      fullPath: '/surveyor'
      preLoaderRoute: typeof SurveyorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty': {
      id: '/empty'
      path: '/empty'
      fullPath: '/empty'
      preLoaderRoute: typeof EmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attestations': {
      id: '/attestations'
      path: '/attestations'
      fullPath: '/attestations'
      preLoaderRoute: typeof AttestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-tokens': {
      id: '/api-tokens'
      path: '/api-tokens'
      fullPath: '/api-tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-valuation': {
      id: '/ai-valuation'
      path: '/ai-valuation'
      fullPath: '/ai-valuation'
      preLoaderRoute: typeof AiValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-timeline': {
      id: '/ai-timeline'
      path: '/ai-timeline'
      fullPath: '/ai-timeline'
      preLoaderRoute: typeof AiTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-summary': {
      id: '/ai-summary'
      path: '/ai-summary'
      fullPath: '/ai-summary'
      preLoaderRoute: typeof AiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-suggestions': {
      id: '/ai-suggestions'
      path: '/ai-suggestions'
      fullPath: '/ai-suggestions'
      preLoaderRoute: typeof AiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-satellite': {
      id: '/ai-satellite'
      path: '/ai-satellite'
      fullPath: '/ai-satellite'
      preLoaderRoute: typeof AiSatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-risk': {
      id: '/ai-risk'
      path: '/ai-risk'
      fullPath: '/ai-risk'
      preLoaderRoute: typeof AiRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendations': {
      id: '/ai-recommendations'
      path: '/ai-recommendations'
      fullPath: '/ai-recommendations'
      preLoaderRoute: typeof AiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-passport': {
      id: '/ai-passport'
      path: '/ai-passport'
      fullPath: '/ai-passport'
      preLoaderRoute: typeof AiPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ocr': {
      id: '/ai-ocr'
      path: '/ai-ocr'
      fullPath: '/ai-ocr'
      preLoaderRoute: typeof AiOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-land-health': {
      id: '/ai-land-health'
      path: '/ai-land-health'
      fullPath: '/ai-land-health'
      preLoaderRoute: typeof AiLandHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-fraud': {
      id: '/ai-fraud'
      path: '/ai-fraud'
      fullPath: '/ai-fraud'
      preLoaderRoute: typeof AiFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-confidence': {
      id: '/ai-confidence'
      path: '/ai-confidence'
      fullPath: '/ai-confidence'
      preLoaderRoute: typeof AiConfidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-boundary': {
      id: '/ai-boundary'
      path: '/ai-boundary'
      fullPath: '/ai-boundary'
      preLoaderRoute: typeof AiBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyor/tools': {
      id: '/surveyor/tools'
      path: '/tools'
      fullPath: '/surveyor/tools'
      preLoaderRoute: typeof SurveyorToolsRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/surveyor/assignments': {
      id: '/surveyor/assignments'
      path: '/assignments'
      fullPath: '/surveyor/assignments'
      preLoaderRoute: typeof SurveyorAssignmentsRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/support/new': {
      id: '/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof SupportNewRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/reports/new': {
      id: '/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof ReportsNewRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/government/permits': {
      id: '/government/permits'
      path: '/permits'
      fullPath: '/government/permits'
      preLoaderRoute: typeof GovernmentPermitsRouteImport
      parentRoute: typeof GovernmentRoute
    }
    '/government/parcels': {
      id: '/government/parcels'
      path: '/parcels'
      fullPath: '/government/parcels'
      preLoaderRoute: typeof GovernmentParcelsRouteImport
      parentRoute: typeof GovernmentRoute
    }
    '/government/disputes': {
      id: '/government/disputes'
      path: '/disputes'
      fullPath: '/government/disputes'
      preLoaderRoute: typeof GovernmentDisputesRouteImport
      parentRoute: typeof GovernmentRoute
    }
    '/government/audit': {
      id: '/government/audit'
      path: '/audit'
      fullPath: '/government/audit'
      preLoaderRoute: typeof GovernmentAuditRouteImport
      parentRoute: typeof GovernmentRoute
    }
    '/fraud/$id': {
      id: '/fraud/$id'
      path: '/$id'
      fullPath: '/fraud/$id'
      preLoaderRoute: typeof FraudIdRouteImport
      parentRoute: typeof FraudRoute
    }
    '/disputes/new': {
      id: '/disputes/new'
      path: '/new'
      fullPath: '/disputes/new'
      preLoaderRoute: typeof DisputesNewRouteImport
      parentRoute: typeof DisputesRoute
    }
    '/disputes/$id': {
      id: '/disputes/$id'
      path: '/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof DisputesIdRouteImport
      parentRoute: typeof DisputesRoute
    }
    '/bank/loans': {
      id: '/bank/loans'
      path: '/loans'
      fullPath: '/bank/loans'
      preLoaderRoute: typeof BankLoansRouteImport
      parentRoute: typeof BankRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/surveyor/assignments/$id': {
      id: '/surveyor/assignments/$id'
      path: '/$id'
      fullPath: '/surveyor/assignments/$id'
      preLoaderRoute: typeof SurveyorAssignmentsIdRouteImport
      parentRoute: typeof SurveyorAssignmentsRoute
    }
    '/properties/$id/verify': {
      id: '/properties/$id/verify'
      path: '/verify'
      fullPath: '/properties/$id/verify'
      preLoaderRoute: typeof PropertiesIdVerifyRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/transfer': {
      id: '/properties/$id/transfer'
      path: '/transfer'
      fullPath: '/properties/$id/transfer'
      preLoaderRoute: typeof PropertiesIdTransferRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/timeline': {
      id: '/properties/$id/timeline'
      path: '/timeline'
      fullPath: '/properties/$id/timeline'
      preLoaderRoute: typeof PropertiesIdTimelineRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/share': {
      id: '/properties/$id/share'
      path: '/share'
      fullPath: '/properties/$id/share'
      preLoaderRoute: typeof PropertiesIdShareRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/satellite': {
      id: '/properties/$id/satellite'
      path: '/satellite'
      fullPath: '/properties/$id/satellite'
      preLoaderRoute: typeof PropertiesIdSatelliteRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/passport-pdf': {
      id: '/properties/$id/passport-pdf'
      path: '/passport-pdf'
      fullPath: '/properties/$id/passport-pdf'
      preLoaderRoute: typeof PropertiesIdPassportPdfRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/ownership': {
      id: '/properties/$id/ownership'
      path: '/ownership'
      fullPath: '/properties/$id/ownership'
      preLoaderRoute: typeof PropertiesIdOwnershipRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/gis-layers': {
      id: '/properties/$id/gis-layers'
      path: '/gis-layers'
      fullPath: '/properties/$id/gis-layers'
      preLoaderRoute: typeof PropertiesIdGisLayersRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/documents': {
      id: '/properties/$id/documents'
      path: '/documents'
      fullPath: '/properties/$id/documents'
      preLoaderRoute: typeof PropertiesIdDocumentsRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/boundary': {
      id: '/properties/$id/boundary'
      path: '/boundary'
      fullPath: '/properties/$id/boundary'
      preLoaderRoute: typeof PropertiesIdBoundaryRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/properties/$id/ai-analysis': {
      id: '/properties/$id/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/properties/$id/ai-analysis'
      preLoaderRoute: typeof PropertiesIdAiAnalysisRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminRegionsRoute: typeof AdminRegionsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminRegionsRoute: AdminRegionsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BankRouteChildren {
  BankLoansRoute: typeof BankLoansRoute
}

const BankRouteChildren: BankRouteChildren = {
  BankLoansRoute: BankLoansRoute,
}

const BankRouteWithChildren = BankRoute._addFileChildren(BankRouteChildren)

interface DisputesRouteChildren {
  DisputesIdRoute: typeof DisputesIdRoute
  DisputesNewRoute: typeof DisputesNewRoute
}

const DisputesRouteChildren: DisputesRouteChildren = {
  DisputesIdRoute: DisputesIdRoute,
  DisputesNewRoute: DisputesNewRoute,
}

const DisputesRouteWithChildren = DisputesRoute._addFileChildren(
  DisputesRouteChildren,
)

interface FraudRouteChildren {
  FraudIdRoute: typeof FraudIdRoute
}

const FraudRouteChildren: FraudRouteChildren = {
  FraudIdRoute: FraudIdRoute,
}

const FraudRouteWithChildren = FraudRoute._addFileChildren(FraudRouteChildren)

interface GovernmentRouteChildren {
  GovernmentAuditRoute: typeof GovernmentAuditRoute
  GovernmentDisputesRoute: typeof GovernmentDisputesRoute
  GovernmentParcelsRoute: typeof GovernmentParcelsRoute
  GovernmentPermitsRoute: typeof GovernmentPermitsRoute
}

const GovernmentRouteChildren: GovernmentRouteChildren = {
  GovernmentAuditRoute: GovernmentAuditRoute,
  GovernmentDisputesRoute: GovernmentDisputesRoute,
  GovernmentParcelsRoute: GovernmentParcelsRoute,
  GovernmentPermitsRoute: GovernmentPermitsRoute,
}

const GovernmentRouteWithChildren = GovernmentRoute._addFileChildren(
  GovernmentRouteChildren,
)

interface PropertiesIdRouteChildren {
  PropertiesIdAiAnalysisRoute: typeof PropertiesIdAiAnalysisRoute
  PropertiesIdBoundaryRoute: typeof PropertiesIdBoundaryRoute
  PropertiesIdDocumentsRoute: typeof PropertiesIdDocumentsRoute
  PropertiesIdGisLayersRoute: typeof PropertiesIdGisLayersRoute
  PropertiesIdOwnershipRoute: typeof PropertiesIdOwnershipRoute
  PropertiesIdPassportPdfRoute: typeof PropertiesIdPassportPdfRoute
  PropertiesIdSatelliteRoute: typeof PropertiesIdSatelliteRoute
  PropertiesIdShareRoute: typeof PropertiesIdShareRoute
  PropertiesIdTimelineRoute: typeof PropertiesIdTimelineRoute
  PropertiesIdTransferRoute: typeof PropertiesIdTransferRoute
  PropertiesIdVerifyRoute: typeof PropertiesIdVerifyRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdAiAnalysisRoute: PropertiesIdAiAnalysisRoute,
  PropertiesIdBoundaryRoute: PropertiesIdBoundaryRoute,
  PropertiesIdDocumentsRoute: PropertiesIdDocumentsRoute,
  PropertiesIdGisLayersRoute: PropertiesIdGisLayersRoute,
  PropertiesIdOwnershipRoute: PropertiesIdOwnershipRoute,
  PropertiesIdPassportPdfRoute: PropertiesIdPassportPdfRoute,
  PropertiesIdSatelliteRoute: PropertiesIdSatelliteRoute,
  PropertiesIdShareRoute: PropertiesIdShareRoute,
  PropertiesIdTimelineRoute: PropertiesIdTimelineRoute,
  PropertiesIdTransferRoute: PropertiesIdTransferRoute,
  PropertiesIdVerifyRoute: PropertiesIdVerifyRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
  PropertiesNewRoute: typeof PropertiesNewRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
  PropertiesNewRoute: PropertiesNewRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsNewRoute: typeof ReportsNewRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsNewRoute: ReportsNewRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SupportRouteChildren {
  SupportIdRoute: typeof SupportIdRoute
  SupportNewRoute: typeof SupportNewRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIdRoute: SupportIdRoute,
  SupportNewRoute: SupportNewRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface SurveyorAssignmentsRouteChildren {
  SurveyorAssignmentsIdRoute: typeof SurveyorAssignmentsIdRoute
}

const SurveyorAssignmentsRouteChildren: SurveyorAssignmentsRouteChildren = {
  SurveyorAssignmentsIdRoute: SurveyorAssignmentsIdRoute,
}

const SurveyorAssignmentsRouteWithChildren =
  SurveyorAssignmentsRoute._addFileChildren(SurveyorAssignmentsRouteChildren)

interface SurveyorRouteChildren {
  SurveyorAssignmentsRoute: typeof SurveyorAssignmentsRouteWithChildren
  SurveyorToolsRoute: typeof SurveyorToolsRoute
}

const SurveyorRouteChildren: SurveyorRouteChildren = {
  SurveyorAssignmentsRoute: SurveyorAssignmentsRouteWithChildren,
  SurveyorToolsRoute: SurveyorToolsRoute,
}

const SurveyorRouteWithChildren = SurveyorRoute._addFileChildren(
  SurveyorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  AiBoundaryRoute: AiBoundaryRoute,
  AiConfidenceRoute: AiConfidenceRoute,
  AiFraudRoute: AiFraudRoute,
  AiLandHealthRoute: AiLandHealthRoute,
  AiOcrRoute: AiOcrRoute,
  AiPassportRoute: AiPassportRoute,
  AiRecommendationsRoute: AiRecommendationsRoute,
  AiRiskRoute: AiRiskRoute,
  AiSatelliteRoute: AiSatelliteRoute,
  AiSuggestionsRoute: AiSuggestionsRoute,
  AiSummaryRoute: AiSummaryRoute,
  AiTimelineRoute: AiTimelineRoute,
  AiValuationRoute: AiValuationRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiTokensRoute: ApiTokensRoute,
  AssistantRoute: AssistantRoute,
  AttestationsRoute: AttestationsRoute,
  BankRoute: BankRouteWithChildren,
  BillingRoute: BillingRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityRoute: CommunityRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DisputesRoute: DisputesRouteWithChildren,
  EmptyRoute: EmptyRoute,
  ErrorRoute: ErrorRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FraudRoute: FraudRouteWithChildren,
  GovernmentRoute: GovernmentRouteWithChildren,
  HelpRoute: HelpRoute,
  ImpactRoute: ImpactRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MobileRoute: MobileRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  RoleSelectRoute: RoleSelectRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SuccessRoute: SuccessRoute,
  SupportRoute: SupportRouteWithChildren,
  SurveyorRoute: SurveyorRouteWithChildren,
  TermsRoute: TermsRoute,
  ValuationRoute: ValuationRoute,
  VerificationRoute: VerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
